Exploring Variation in Recorded Cod Landings in the U.S. From 1950 to 2021
================
by "Not Our Names", aka Delphine, Reese and Kristin

# Summary

#### Introduction 
As a group, we worked with a dataset collected by NOAA Fisheries surrounding annual Cod landings in the United States from 1950 to 2021. The three of us share a mutual interest in marine science, and whilst all three of us typically focus on different aspects of marine science, we were keen on exploring this dataset for our final project. We had a total of 10 variables in our dataset, and choosing five of these variables, we quickly brainstormed the most effective visualizations, creating a few more along the way.
  
Immediately within the dataset, we could see that various data were collected in different states along the Atlantic and Pacific coasts. This assisted us in understanding what type of visualizations we would like to make with our dataset and what information would go well with said visualizations. The best way to utilize this dataset would be to create representative graphs of Cod landing fluctuations in several aspects. We started discussing what ways we could do this that would be accessible and readable to a broader audience, and we began considering creating an animated plot representing Cod landings by year, an interactive plot showing variables on a year-by-year basis, a series of maps that show how many pounds of Cod (in trillions) were caught by each state that participated in the U.S. Cod fishery, along with a graph that shows where in our dataset we had missing data points (which did occur several times after the year 2000). 

We also considered if any factors, such as legislation and fishery crashes, would have influenced the Cod fisheries over the years. Following 1993, there was a significant crash in the population of Cod in the Gulf of Maine, but this did not hugely affect the overall trends of Cod fishing in the Atlantic. Canada called a moratorium into effect in 1992, halting all Cod fishing temporarily and putting over 30,000 people out of a job. However, this did not affect our data since we only decided to focus on the United States. Additionally, the Pacific Cod fisheries have laws regulating catch gear, catch locations, and quotas, which keep the overall catch trends reasonably consistent. So while we researched catch fluctuations, there were no significant North American findings.
  
Unfortunately, as we neared the end of the time we had to work on this project, we began running into issue after issue, and soon realized that the data within our dataset is factually incorrect. With no time to start from scratch with a whole new dataset, we decided to proceed with our dataset as if it had been correct, acknowledging the fact that it is inaccurate in our final presentation.
  
### Exploring Wider Implications of Our Dataset:
#### Missing data
While working with the Cod landing dataset, we noticed an abundance of missing recreational landings data throughout 1950-2021. We visualized the missing Cod landing values in two scatterplots to highlight which fishing type had missing data and when. Before the 1980s, there was no record of recreational Cod landings. The missing points after the 1990s display recreational Cod landings activity was recorded, even if the values weren’t defined. Overall, the total and recreational Cod landings conclusions aren’t entirely accurate, and therefore represent a big limitation to our exploration. 
Landings by Species and Fishing Types

The first aspect we wanted to explore with this dataset was a general overview of how the recorded Pacific and Atlantic Cod landings had varied over time. We opted for an animated visualization using an image of a Cod moving and leaving a trace to show the fluctuations of millions of pounds recorded each year. This visualization was faceted to better compare the trend for the Pacific and Atlantic Cods. This exploration allowed us to discover more recorded landings of the Atlantic Cod than the Pacific Cod. We also explored general trends of the recorded data and saw that the Atlantic Cod landings peaked in a few specific years, namely 1997 and 2011. Pacific Cod landings in these same years were smaller and closer to two or three times less than the values for Atlantic Cod. The Pacific Cod peaked in 1997 and 2012.

Building off our understanding of the data through our first visualization, we wanted to explore the specifics of these recorded landings further and look at the variation in ratios of recorded commercial and recreational landings over the years. We opted for a Plotly interactive bar chart colored by fishing types. This interactive visualization was highly informative as it allowed the viewer to hover over specific bars and have a condensed summary of the year, weight of landings, and fishing types. More than being informative, using this interactive graph was a great way to make these data more accessible. For the Atlantic Cod, we discovered a drastic variation of recorded landings for recreational and commercial fishing. Notably, an interesting representation of such occurs from 2016 to 2021, as this visualization depicts that the overall decrease in landings occurred mostly because of a decrease in recorded commercial landings. Before 2016, these data showed ratios where the recorded values of commercial landings were higher than those of recreational landings for Atlantic Cod, but also for Pacific Cod. The Pacific Cod facet also reveals this same trend where recorded commercial landings are often the reason for total variation in landings. 

#### Maps of Overall Commercial Value by Species

The second aspect we highlighted in the Cod landing dataset was how the monetary value of Atlantic and Pacific Cod landings in 1950, 1980, 1999, 2008, 2018, and 2021 varied in relative states. We asked this question to explore which state's economic growth was most affected by the fluctuation depicted by the commercial Cod landings. We highlighted these years to best visualize the rate of change in commercial Cod landing profits across the decades for the Cod species. No economic variables were available or recorded for recreational fishing since these Cod are not for profit. Therefore, our faceted maps only represent commercial Cod landing profits. As we explored the data and discovered there was a drastic difference in monetary value between Atlantic and Pacific commercial Cod landings. We decided to separate our visualization to more accurately represent each of the United States’ coasts.
Our visualizations highlight how commercial Atlantic and Pacific Cod landings, as well as economic growth for specific states have declined significantly in the last few decades. Notably, Massachusetts benefited the most from Cod landings along the east coast, with a peak of over 27 million dollars in profit in 1980. Also, the Atlantic Cod landings map shows that this state’s commercial profit peaked around the 1980s, decreased for a few more years, and then increased again in 2008. However, our visualization focused on the Pacific Cod landing profits only highlighted a peak in 2008, with a value of over 280 million dollars in Alaska alone. Since Alaska's economy benefits more than any other state, the drop in Pacific Cod landings affected them the most. Overall, these visualizations highlight that since 2008, the monetary value of Atlantic and Pacific Cod were really low compared to 2018 and 2021. We found it interesting that on the west and east coast, states like California, Maryland, Delaware, North Carolina, and Virginia only benefited from Cod landings in specific years, which could be explained by the minimal or missing data of recorded landings scattered throughout the decades.  

### Limitations
Throughout the time we spent coworking with this dataset, we came to realize its various flaws and limitations. Notably, as we started creating visualizations of total landings over time distinguishing  fishing types, we discovered that there was no recorded data for recreational fishing before 1980. However, these were not shown as “missing data” when we explored our N/A values at the beginning of our exploration, since these rows were simply missing rather than present, but containing missing values. As we eventually did more research on background information and context as to how these data were collected, we came to understand that there was not a lot of additional information to be found. We eventually realized that this lack of context represented a great limitation to our dataset, since we could not engage into wider implications shown by these data. As we started further engaging in what the visualizations we made were representing, we eventually came to the conclusion that the trends of fluctuating Cod landings over time shown by our visualizations appeared to be factually inaccurate in comparison to research about historical decline in cod populations in the past decades. As so much work had been done by the time we realized this issue, we decided to complete our exploration with this dataset, knowing that the stories told by our visualizations were probably not factually accurate. We therefore want to acknowledge that the visualizations we created accurately represent the dataset we were working with, but that this dataset is probably inaccurate and a misrepresentation of the actual trends of fluctuating Cod landings in the U.S from 1950 to 2021.

#### Conclusion
To conclude, we want to acknowledge how this project has allowed us to further develop our coding skills in R and challenged us in multiple ways, from trying new visualizations to discovering the dataset we had been working with for so long was probably unfactual. That being said, if these data had been right, we think a great extension to this exploration could have been to include recorded Canadian landings. It would have been really interesting to compare both countries, and also explore how different policies and regulations affect the landings across borders. Thus, we can say that this project enhanced our understanding and experience of coding with R while teaching us lessons about data reliability and  giving us valuable experience of collaborating and troubleshooting as a team. 
  
## Presentation

Our presentation can be found [here](https://docs.google.com/presentation/d/1y0A1QFq4b1UTT74NAKcLMbQe4-UAJDUbxPGwKhqE8AE/edit?usp=sharing.html).

## Data

NOAA, 2023, Atlantic and Pacific Cod Landing (1950-2021), Kaggle, https://www.kaggle.com/datasets/mattop/atlantic-and-pacific-cod-landings-1950-2021.

## References

NOAA, 2023, Atlantic and Pacific Cod Landing (1950-2021), Kaggle, https://www.kaggle.com/datasets/mattop/atlantic-and-pacific-cod-landings-1950-2021.

Fisheries, NOAA. “Pacific Cod | NOAA Fisheries.” NOAA, 18 Aug. 2020, www.fisheries.noaa.gov/species/pacific-cod.

“Collapse of the Atlantic Northwest Cod Fishery.” Wikipedia, 28 Feb. 2023, en.wikipedia.org/wiki/Collapse_of_the_Atlantic_northwest_cod_fishery

“Cod Moratorium: How Newfoundland’s Cod Industry Disappeared Overnight.” Canadiangeographic.ca, canadiangeographic.ca/articles/cod-moratorium-how-newfoundlands-cod-industry-disappeared-overnight/.

